/* O COMANDO SELECT*/
/* TODO BANCO FAZ SELEÇÃO, PROJEÇÃO E JUNÇÃO*/
/*FAZ O BANCO MOSTRAR O QUE A GENTE QUER*/
SELECT NOW() AS DATA_HORA;
SELECT 'MEU NOME';

/* ALIAS D COLUNAS*/

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/*APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;



