/* Modelagem Banco*/

CLIENTE

NOME - CARACTER (30)
CPF - NUMERICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

/* ProcessoS de Modelagem*/

/* FASE 01 E 02 - ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LOGICAL - QUALQUER PROGRAMA D EMODELAGEM
/*	ENTIDADE = TABELA
	CAMPOS = ATRIBUTOS
	*/
/* DBA/AD */
MODELAGEM FISICA - SCRIPTS DE BANCO

/* INICIANDO A MODELAGEM-FISICA*/
/* CRIANDO O BANCO DE DADOS*/

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO*/

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES*/

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO*/

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRURUTA DE UMA TABELA*/

DESC CLIENTE;